### ISSUE TITLE
Net Standard Socket Exception

### ISSUE THREAD

**Issue by brswan** [1iveowl/SimpleHttpListener.Rx#15]
NetStandard: 2.0.3
Xamarin Forms: 3.3.0.967583

I am using Xamarin Forms to host a HTTP Server within my app.  I am serving local webpages.  One page uses React and video player.

I will get a socket exception.  I can restart the server, but the web page does not respond to input anymore.  

{System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
  at System.Net.Sockets.Socket.EndSend (System.IAsyncResult asyncResult) [0x00012] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
  at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x00057] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x0009b] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
  at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
  at (wrapper delegate-invoke) System.Func`3[System.IO.Stream,System.IAsyncResult,System.Threading.Tasks.VoidTaskResult].invoke_TResult_T1_T2(System.IO.Stream,System.IAsyncResult)
  at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at SimpleHttpListener.Rx.Service.HttpSender+<SendTcpResponseAsync>d__0.MoveNext () [0x000c8] in V:\GitHub\SimpleHttpListener.Rx\src\main\SimpleHttpListener.Rx\Service\HttpSender.cs:30

**Comment by 1iveowl** [comment]
I see you closed this again. What turned out to be the issue?

**Comment by brswan** [comment]
It ended up being two issues that I thought were one.

I used your library because the NETStandard library throws the same
exception but it kills the app. I cannot catch it.

With your library I can catch it and ignore it.

I thought the exception was preventing further requests from being
processed but it turns out that my streaming video kept a request open.
The Observable.FromAsync call was preventing other requests until the video
was fully viewed.


So it turns out it was unrelated and I had to use SelectMany and remove the
Concat call.

I can send you the code tomorrow as it's on my work machine and I am home
now.

Thanks.

**Comment by brswan** [comment]
Would you have any idea why only on Android, my server is very slow in
responding.


I see it does not take very long to reply with the stream data.  The
requests from the client are being queued and delay.
Any help or a point in the right direction would be greatly appreciated!

                  m_Listener = m_TcpListener
                            .ToHttpListenerObservable(cts.Token)
                            .Do(r =>
                            {
                                //Debug.WriteLine($"Remote Uri:
{r.RequestUri}");
                                //Debug.WriteLine($"Remote Address:
{r.RemoteIpEndPoint.Address}");
                                //Debug.WriteLine($"Remote Port:
{r.RemoteIpEndPoint.Port}");

//Debug.WriteLine("--------------***-------------");
                            })
                            // Send reply to browser
                            .SelectMany(r =>
                            {
                                //Debug.WriteLine($"Send Reply:
{r.RequestUri}");
                                return Observable.FromAsync(() =>
                                {
                                    //Debug.WriteLine($"Inside From Async:
{r.RequestUri}");
                                    return SendResponseAsync(r, httpSender);
                                });
                            })
                            //.Concat()
                            .Subscribe(r =>
                            {
                                //Debug.WriteLine("Reply sent.");
                            },
                            ex =>
                            {
                                string error = $"Http Serve Error:
{ex.Message}";
                                s_Logger.Error(error);
                                Crashes.TrackError(ex, new
Dictionary<string, string>
                                {
                                    { "Error", error }
                                });
                            },
                            () =>
                            {
                                //Debug.WriteLine("##### Completed.");
                            });
