### ISSUE TITLE
support .net framework 4.5 

### ISSUE THREAD

**Issue by behroozbc** [1iveowl/SimpleHttpListener.Rx#17]
hi 
can you support .net framework 4.5 ?

**Comment by 1iveowl** [comment]
Sry, but no. The library is .NET Standard 2.0+, which means .Net framework 4.6.1+

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by behroozbc** [comment]
I know but I want use in. Net framework 4.5
Please support
