### ISSUE TITLE
Handle more than GET

### ISSUE THREAD

**Issue by dapug** [1iveowl/SimpleHttpListener.Rx#7]
Try posting to your listener.  Nothing happens.  GET works fine.  Used exact code from your test sample and doc page here.

If the incoming request has ANY content in the body, SimpleHttpListener.Rx doesn't respond, SendResponseAsync() is never fired.  If I Post null (no body), however, I do see SendResponseAsync() fires and the request.Method is POST.

**Comment by 1iveowl** [comment]
Thank you.

I'm travelling the next 8 days. I'll look at it when I get some more time. Looks like a bug in the parsing. Feel free to have a look at it too. The code is very simple.

**Comment by 1iveowl** [comment]
@dapug I just tried to test this with Postman. GET works fine, so does POST with and without BODY content. 

I used the test console included here in the repo.

Any insights?

**Comment by dapug** [comment]
Sorry, I've gotten totally slammed with other things at work and haven't had a chance to dig further.  I was using Fiddler rather than Postman... but can't see why that should matter.  I will report back as soon as I have a chance.  You can leave open or close this in the meantime, in case I find nothing, and given you've verified it's ok on you're end.

Epic awesome project BTW.

**Comment by 1iveowl** [comment]
Did it work?

**Comment by 1iveowl** [comment]
No news in 10 days. I assume that it works ;-)
