### ISSUE TITLE
[Android] Compile issues, emulator support

### ISSUE THREAD

**Issue by AndreiMisiukevich** [1iveowl/SimpleHttpListener.Rx#9]
Hi, thank you for great library
Does it support Android? (I think yes).

So, there is a problem with that

![image](https://user-images.githubusercontent.com/10124814/48735146-8fe18980-ec58-11e8-9b6a-1e879d36be1b.png)

I get next compile error on Android
![image](https://user-images.githubusercontent.com/10124814/48735190-bb647400-ec58-11e8-9ef4-424752ae8b53.png)

if I try to add System.Threading.Tasks.Extensions v.4.4.0 to android project manually, it fixes compile error, but still doesn't work.

**REPRO**
https://github.com/AndreiMisiukevich/HotReload

- Open solution above
- Open HotReloader.cs (Find it via navigator)
- Set breakpoint in line 116 (HandleRequestAsync method)
- Start Xamarin.Forms.HotReload.Sample.Android
- Try to open base address via browser (get request)

Expected result: we hit breakpoint by get request
Actual result: nothing happens

iOS work like a charm (you can start Xamarin.Forms.HotReload.Sample.iOS and make sure it)

Did i miss something?

**Comment by 1iveowl** [comment]
There's currently an issue with System.Reactive for Android dotnet/reactive#803

I'm waiting for this to be fixed. The issue is not related to this library.

**Comment by 1iveowl** [comment]
This library is quite an improvement.

Try downgrading to System.Reactive 4.0.0. Let me know if it works. I'll create a new NuGet with it until they get the issue fixed.

**Comment by AndreiMisiukevich** [comment]
@1iveowl it's impossible

You package has constraint for System.Reactive  
![image](https://user-images.githubusercontent.com/10124814/48739388-e8b71f00-ec64-11e8-973d-866af8ee9a4f.png)

**Comment by 1iveowl** [comment]
I just published an update. Should be there in a few minutes. Could you try v6.0.6

**Comment by 1iveowl** [comment]
If v6.0.6 doens't work then please try: 6.0.6-pre-release2.

v6.0.6 uses System.Reactive 4.1.2
v6.0.6-pre-release2 uses System.Reative 4.0.0

**Comment by AndreiMisiukevich** [comment]
@1iveowl thanks, i'll try it tomorrow and come back with feedback)

**Comment by 1iveowl** [comment]
@AndreiMisiukevich any update on this?

**Comment by AndreiMisiukevich** [comment]
@1iveowl yes, i tried on genymotion emulator and i guess it fails by timeout. Really can't understand if it your issue or i do something wrong.

Today i want to try with real device (I will connect to the same wi-fi hotspot and try to send get request)

Have you change to try as well?

**Comment by AndreiMisiukevich** [comment]
@1iveowl ok, it works fine on **v6.0.5** fine too, but i had to add System.Threading.Tasks.Extensions v.4.4.0 directly to android project.

**v6.0.6** - the same behavior as on 6.0.5 (cannot compile until add System.Threading.Tasks.Extensions v.4.4.0 directly to android project.)

**v6.0.6-pre2** - works fine without need to execute any additional steps.
But beta-version doesn't sound well for me, as i develop nuget package and i can't use beta-versions as constraint.

What do you think about creating stable package with such version?

**Comment by AndreiMisiukevich** [comment]
@1iveowl but i still don't understand, why it doesn't work on GenyMotion emulator?

Tried with both available emulators, but it fails by timeout.
![image](https://user-images.githubusercontent.com/10124814/48923594-fff24880-eec0-11e8-8416-7536b2e6f0ca.png)

http://10.0.3.15:8000

hmm.. it looks like any emulator's firewall prevents accessing. Any ideas?

**Comment by 1iveowl** [comment]
As mentioned, this is an issue with System.Reactive 4.1.2. 

I could downgrade to System.Reactive 4.0.0, and in fact that is exactly what I do in v6.0.6-preview2 (nothing else has changed in this library), however there are many improvements in System.Reactive 4.1.2 so I don't want the latest version of SimpleHttpListener.Rx to use System.Reactive 4.0.0. 

If you look careful at dotnet/reactive#803 then there seems to be a work around: [Downgrading System.Threading.Tasks.Extension from 4.5.1 to 4.4.0](https://github.com/dotnet/reactive/issues/803#issuecomment-415986547). Could you try this work-around and let me know if it works for you?

**Comment by 1iveowl** [comment]
I changed my mind. 

Please use v6.1.0 is now uses System.Reactive 4.0.0 and will do so until dotnet/reactive#803 have been fixed.

**Comment by AndreiMisiukevich** [comment]
@1iveowl thanks)
Great plugin, well done
